create table Car_Features (
	car_feature_ID INT,
	car_feature_description VARCHAR(50),
	PRIMARY KEY(car_feature_id)
);
insert into Car_Features (car_feature_id, car_feature_description) values (1, 'Advanced intangible throughput');
insert into Car_Features (car_feature_id, car_feature_description) values (2, 'Sharable directional flexibility');
insert into Car_Features (car_feature_id, car_feature_description) values (3, 'Pre-emptive fresh-thinking portal');
insert into Car_Features (car_feature_id, car_feature_description) values (4, 'Phased system-worthy Graphic Interface');
insert into Car_Features (car_feature_id, car_feature_description) values (5, 'Business-focused 3rd generation standardization');
insert into Car_Features (car_feature_id, car_feature_description) values (6, 'Extended attitude-oriented complexity');
insert into Car_Features (car_feature_id, car_feature_description) values (7, 'Function-based user-facing groupware');
insert into Car_Features (car_feature_id, car_feature_description) values (8, 'Enhanced bifurcated framework');
insert into Car_Features (car_feature_id, car_feature_description) values (9, 'Up-sized context-sensitive conglomeration');
insert into Car_Features (car_feature_id, car_feature_description) values (10, 'Optional analyzing task-force');
insert into Car_Features (car_feature_id, car_feature_description) values (11, 'Object-based responsive function');
insert into Car_Features (car_feature_id, car_feature_description) values (12, 'Decentralized leading edge capacity');
insert into Car_Features (car_feature_id, car_feature_description) values (13, 'Profit-focused web-enabled help-desk');
insert into Car_Features (car_feature_id, car_feature_description) values (14, 'Function-based didactic conglomeration');
insert into Car_Features (car_feature_id, car_feature_description) values (15, 'Synergistic asynchronous collaboration');
insert into Car_Features (car_feature_id, car_feature_description) values (16, 'Quality-focused radical Graphical User Interface');
insert into Car_Features (car_feature_id, car_feature_description) values (17, 'Multi-lateral upward-trending standardization');
insert into Car_Features (car_feature_id, car_feature_description) values (18, 'Mandatory fresh-thinking challenge');
insert into Car_Features (car_feature_id, car_feature_description) values (19, 'Managed leading edge data-warehouse');
insert into Car_Features (car_feature_id, car_feature_description) values (20, 'Optional fresh-thinking help-desk');
insert into Car_Features (car_feature_id, car_feature_description) values (21, 'Self-enabling intermediate conglomeration');
insert into Car_Features (car_feature_id, car_feature_description) values (22, 'Enhanced client-server solution');
insert into Car_Features (car_feature_id, car_feature_description) values (23, 'Visionary transitional flexibility');
insert into Car_Features (car_feature_id, car_feature_description) values (24, 'Reduced regional collaboration');
insert into Car_Features (car_feature_id, car_feature_description) values (25, 'Organized non-volatile support');
insert into Car_Features (car_feature_id, car_feature_description) values (26, 'User-friendly zero tolerance budgetary management');
insert into Car_Features (car_feature_id, car_feature_description) values (27, 'Up-sized asynchronous alliance');
insert into Car_Features (car_feature_id, car_feature_description) values (28, 'Automated multimedia open architecture');
insert into Car_Features (car_feature_id, car_feature_description) values (29, 'De-engineered interactive benchmark');
insert into Car_Features (car_feature_id, car_feature_description) values (30, 'Reduced web-enabled groupware');
insert into Car_Features (car_feature_id, car_feature_description) values (31, 'Proactive bifurcated groupware');
insert into Car_Features (car_feature_id, car_feature_description) values (32, 'Total zero defect application');
insert into Car_Features (car_feature_id, car_feature_description) values (33, 'Multi-channelled analyzing capability');
insert into Car_Features (car_feature_id, car_feature_description) values (34, 'Programmable systematic migration');
insert into Car_Features (car_feature_id, car_feature_description) values (35, 'Organized heuristic access');
insert into Car_Features (car_feature_id, car_feature_description) values (36, 'User-friendly 4th generation core');
insert into Car_Features (car_feature_id, car_feature_description) values (37, 'Vision-oriented 6th generation moderator');
insert into Car_Features (car_feature_id, car_feature_description) values (38, 'Intuitive zero administration firmware');
insert into Car_Features (car_feature_id, car_feature_description) values (39, 'Exclusive leading edge ability');
insert into Car_Features (car_feature_id, car_feature_description) values (40, 'Managed upward-trending customer loyalty');
insert into Car_Features (car_feature_id, car_feature_description) values (41, 'Customizable 5th generation Graphic Interface');
insert into Car_Features (car_feature_id, car_feature_description) values (42, 'Switchable intermediate hub');
insert into Car_Features (car_feature_id, car_feature_description) values (43, 'Expanded non-volatile alliance');
insert into Car_Features (car_feature_id, car_feature_description) values (44, 'Focused fault-tolerant leverage');
insert into Car_Features (car_feature_id, car_feature_description) values (45, 'Customizable empowering methodology');
insert into Car_Features (car_feature_id, car_feature_description) values (46, 'Enhanced multi-tasking capacity');
insert into Car_Features (car_feature_id, car_feature_description) values (47, 'Switchable maximized intranet');
insert into Car_Features (car_feature_id, car_feature_description) values (48, 'Persevering context-sensitive monitoring');
insert into Car_Features (car_feature_id, car_feature_description) values (49, 'Enterprise-wide multi-state product');
insert into Car_Features (car_feature_id, car_feature_description) values (50, 'Implemented next generation moderator');
insert into Car_Features (car_feature_id, car_feature_description) values (51, 'Optimized logistical time-frame');
insert into Car_Features (car_feature_id, car_feature_description) values (52, 'Down-sized 24/7 data-warehouse');
insert into Car_Features (car_feature_id, car_feature_description) values (53, 'Reverse-engineered well-modulated challenge');
insert into Car_Features (car_feature_id, car_feature_description) values (54, 'Diverse eco-centric secured line');
insert into Car_Features (car_feature_id, car_feature_description) values (55, 'Reduced mobile array');
insert into Car_Features (car_feature_id, car_feature_description) values (56, 'Balanced empowering synergy');
insert into Car_Features (car_feature_id, car_feature_description) values (57, 'Right-sized web-enabled projection');
insert into Car_Features (car_feature_id, car_feature_description) values (58, 'Open-source high-level workforce');
insert into Car_Features (car_feature_id, car_feature_description) values (59, 'Balanced zero defect contingency');
insert into Car_Features (car_feature_id, car_feature_description) values (60, 'Decentralized empowering approach');
insert into Car_Features (car_feature_id, car_feature_description) values (61, 'Cross-group analyzing definition');
insert into Car_Features (car_feature_id, car_feature_description) values (62, 'Enterprise-wide homogeneous hardware');
insert into Car_Features (car_feature_id, car_feature_description) values (63, 'Synergistic background collaboration');
insert into Car_Features (car_feature_id, car_feature_description) values (64, 'Assimilated dynamic artificial intelligence');
insert into Car_Features (car_feature_id, car_feature_description) values (65, 'Distributed composite contingency');
insert into Car_Features (car_feature_id, car_feature_description) values (66, 'Public-key solution-oriented migration');
insert into Car_Features (car_feature_id, car_feature_description) values (67, 'Public-key tangible function');
insert into Car_Features (car_feature_id, car_feature_description) values (68, 'Persistent foreground data-warehouse');
insert into Car_Features (car_feature_id, car_feature_description) values (69, 'Reverse-engineered next generation leverage');
insert into Car_Features (car_feature_id, car_feature_description) values (70, 'Implemented even-keeled methodology');
insert into Car_Features (car_feature_id, car_feature_description) values (71, 'User-friendly regional utilisation');
insert into Car_Features (car_feature_id, car_feature_description) values (72, 'Operative zero tolerance conglomeration');
insert into Car_Features (car_feature_id, car_feature_description) values (73, 'Secured stable frame');
insert into Car_Features (car_feature_id, car_feature_description) values (74, 'Centralized asynchronous artificial intelligence');
insert into Car_Features (car_feature_id, car_feature_description) values (75, 'Synergized secondary infrastructure');
insert into Car_Features (car_feature_id, car_feature_description) values (76, 'Future-proofed 4th generation model');
insert into Car_Features (car_feature_id, car_feature_description) values (77, 'User-centric bandwidth-monitored help-desk');
insert into Car_Features (car_feature_id, car_feature_description) values (78, 'Multi-tiered value-added middleware');
insert into Car_Features (car_feature_id, car_feature_description) values (79, 'Sharable modular challenge');
insert into Car_Features (car_feature_id, car_feature_description) values (80, 'Programmable stable task-force');
insert into Car_Features (car_feature_id, car_feature_description) values (81, 'Customizable fault-tolerant flexibility');
insert into Car_Features (car_feature_id, car_feature_description) values (82, 'Implemented holistic moderator');
insert into Car_Features (car_feature_id, car_feature_description) values (83, 'Proactive dynamic utilisation');
insert into Car_Features (car_feature_id, car_feature_description) values (84, 'Stand-alone intermediate artificial intelligence');
insert into Car_Features (car_feature_id, car_feature_description) values (85, 'Customizable interactive alliance');
insert into Car_Features (car_feature_id, car_feature_description) values (86, 'Distributed uniform info-mediaries');
insert into Car_Features (car_feature_id, car_feature_description) values (87, 'Front-line optimizing ability');
insert into Car_Features (car_feature_id, car_feature_description) values (88, 'Inverse homogeneous portal');
insert into Car_Features (car_feature_id, car_feature_description) values (89, 'Pre-emptive high-level definition');
insert into Car_Features (car_feature_id, car_feature_description) values (90, 'Face to face maximized neural-net');
insert into Car_Features (car_feature_id, car_feature_description) values (91, 'Horizontal exuding workforce');
insert into Car_Features (car_feature_id, car_feature_description) values (92, 'Synergized non-volatile monitoring');
insert into Car_Features (car_feature_id, car_feature_description) values (93, 'Ergonomic demand-driven utilisation');
insert into Car_Features (car_feature_id, car_feature_description) values (94, 'Intuitive 6th generation monitoring');
insert into Car_Features (car_feature_id, car_feature_description) values (95, 'Mandatory leading edge extranet');
insert into Car_Features (car_feature_id, car_feature_description) values (96, 'Virtual dynamic analyzer');
insert into Car_Features (car_feature_id, car_feature_description) values (97, 'Operative asymmetric methodology');
insert into Car_Features (car_feature_id, car_feature_description) values (98, 'Self-enabling empowering core');
insert into Car_Features (car_feature_id, car_feature_description) values (99, 'Profit-focused system-worthy access');
insert into Car_Features (car_feature_id, car_feature_description) values (100, 'Grass-roots systemic projection');
