create table Finance_Companies (
	finance_Company_ID INT,
	finance_Company_Name VARCHAR(50),
	other_Details VARCHAR(70),
	PRIMARY KEY(finance_Company_ID)
);
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (1, 'Devpulse', 'Digitized');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (2, 'Ntags', 'Inverse');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (3, 'Aimbu', 'foreground');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (4, 'Leenti', 'context-sensitive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (5, 'Flashpoint', 'encoding');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (6, 'Yakidoo', 'system-worthy');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (7, 'Yodel', 'moderator');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (8, 'Zoonder', 'tangible');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (9, 'Wikido', 'client-server');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (10, 'Flashspan', 'software');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (11, 'Babblestorm', 'bandwidth-monitored');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (12, 'Ozu', 'analyzing');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (13, 'Zoomdog', 'well-modulated');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (14, 'Zoonoodle', 'moderator');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (15, 'Voolia', 'Multi-tiered');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (16, 'Fanoodle', 'Monitored');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (17, 'Feedbug', 'access');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (18, 'Flipopia', 'strategy');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (19, 'InnoZ', 'responsive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (20, 'Kare', 'grid-enabled');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (21, 'Mydo', 'Front-line');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (22, 'Eabox', 'Multi-tiered');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (23, 'Eire', 'workforce');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (24, 'Divanoodle', 'Exclusive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (25, 'Vidoo', 'knowledge user');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (26, 'Innotype', 'Advanced');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (27, 'Vitz', 'Exclusive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (28, 'Abatz', 'Pre-emptive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (29, 'Quaxo', 'Cross-platform');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (30, 'Meejo', 'Phased');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (31, 'Mynte', 'exuding');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (32, 'Dazzlesphere', 'actuating');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (33, 'Voolith', 'dedicated');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (34, 'Edgewire', 'moderator');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (35, 'Linktype', 'local');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (36, 'Jazzy', 'actuating');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (37, 'Photobug', 'parallelism');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (38, 'Vinder', 'definition');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (39, 'Yodoo', 'Realigned');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (40, 'Browsezoom', 'solution-oriented');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (41, 'Quinu', '24/7');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (42, 'Roomm', 'incremental');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (43, 'Gabvine', 'Compatible');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (44, 'Yabox', 'Universal');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (45, 'Skipstorm', 'Monitored');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (46, 'Kazu', 'Integrated');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (47, 'Wikizz', 'orchestration');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (48, 'Mudo', 'Progressive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (49, 'Photofeed', 'model');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (50, 'Vinte', '3rd generation');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (51, 'Meejo', 'cohesive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (52, 'Feednation', '3rd generation');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (53, 'Skajo', 'Multi-channelled');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (54, 'Kwilith', 'Persevering');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (55, 'Gabcube', 'neural-net');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (56, 'Jamia', 'disintermediate');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (57, 'Trilia', 'Extended');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (58, 'Jabbertype', 'local');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (59, 'Voonyx', 'fresh-thinking');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (60, 'Kimia', 'portal');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (61, 'Kwimbee', 'Progressive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (62, 'Tavu', 'encompassing');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (63, 'Quatz', 'support');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (64, 'Browsezoom', 'dedicated');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (65, 'Dabshots', 'synergy');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (66, 'Twimbo', 'full-range');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (67, 'Kwinu', 'standardization');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (68, 'Fivespan', 'info-mediaries');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (69, 'Edgeclub', 'encoding');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (70, 'Katz', 'Self-enabling');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (71, 'Digitube', 'Networked');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (72, 'Riffpedia', 'national');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (73, 'Tekfly', 'Universal');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (74, 'Podcat', 'Upgradable');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (75, 'Eayo', 'mission-critical');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (76, 'Jayo', 'matrix');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (77, 'Browsedrive', 'clear-thinking');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (78, 'Fivespan', 'Proactive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (79, 'Fiveclub', 'Intuitive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (80, 'Ozu', 'collaboration');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (81, 'Realfire', 'Configurable');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (82, 'Leenti', 'national');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (83, 'Innotype', 'methodical');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (84, 'Jabbertype', 'Object-based');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (85, 'Dynabox', 'Organized');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (86, 'Meevee', 'Realigned');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (87, 'Wikido', 'Down-sized');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (88, 'Thoughtstorm', 'Business-focused');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (89, 'Kimia', 'Automated');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (90, 'Mycat', 'alliance');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (91, 'Zoombox', 'multimedia');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (92, 'Leenti', 'ability');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (93, 'Youbridge', 'Optional');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (94, 'Gigazoom', 'background');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (95, 'Voolith', 'radical');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (96, 'Reallinks', 'analyzing');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (97, 'Rhyzio', 'user-facing');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (98, 'Fiveclub', 'customer loyalty');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (99, 'Oba', 'zero administration');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (100, 'Buzzbean', 'website');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (101, 'Midel', 'functionalities');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (102, 'Bluezoom', 'Advanced');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (103, 'Aimbo', 'Assimilated');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (104, 'Photolist', 'infrastructure');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (105, 'Riffwire', 'projection');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (106, 'Twimbo', 'Virtual');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (107, 'Shuffledrive', 'interactive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (108, 'Dynabox', 'framework');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (109, 'Brainverse', 'reciprocal');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (110, 'Ailane', 'Triple-buffered');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (111, 'Blogspan', 'fresh-thinking');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (112, 'Buzzdog', 'Persistent');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (113, 'Skinder', 'firmware');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (114, 'Twitterwire', 'success');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (115, 'Flipopia', 'Monitored');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (116, 'Blognation', 'Fully-configurable');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (117, 'Meemm', 'Realigned');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (118, 'Kanoodle', 'bottom-line');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (119, 'Thoughtblab', 'User-friendly');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (120, 'Twitterbridge', 'global');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (121, 'Ntag', 'Object-based');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (122, 'Feednation', 'open architecture');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (123, 'Browsedrive', 'migration');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (124, 'Fivebridge', 'Reduced');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (125, 'Dabtype', 'monitoring');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (126, 'Wikibox', 'Ergonomic');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (127, 'Livetube', 'Upgradable');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (128, 'Photospace', 'budgetary management');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (129, 'Kamba', 'Operative');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (130, 'Yata', 'knowledge user');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (131, 'Centimia', 'intermediate');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (132, 'Brainbox', 'Realigned');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (133, 'Myworks', 'time-frame');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (134, 'Twitterbridge', 'transitional');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (135, 'Jaxspan', 'directional');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (136, 'Edgeclub', 'Total');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (137, 'Tazz', 'encoding');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (138, 'Quinu', 'Re-engineered');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (139, 'Zooveo', 'architecture');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (140, 'Jatri', 'internet solution');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (141, 'Camido', 'heuristic');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (142, 'Realblab', 'access');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (143, 'Eamia', 'Seamless');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (144, 'Mynte', 'Reverse-engineered');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (145, 'Tagtune', 'utilisation');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (146, 'Kare', 'Fully-configurable');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (147, 'Topdrive', 'database');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (148, 'Zoomcast', 'encoding');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (149, 'Brainbox', 'Face to face');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (150, 'Skyvu', 'Total');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (151, 'Skiptube', 'upward-trending');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (152, 'Blogtags', 'Total');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (153, 'Meetz', 'standardization');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (154, 'Rhyloo', 'methodical');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (155, 'Kazio', 'Customizable');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (156, 'Bubbletube', 'structure');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (157, 'Flipopia', 'asymmetric');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (158, 'Divanoodle', 'matrix');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (159, 'Ainyx', 'open system');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (160, 'Cogilith', 'open system');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (161, 'Tagpad', 'dedicated');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (162, 'Dynazzy', 'hardware');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (163, 'Kayveo', 'Reduced');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (164, 'Livepath', 'next generation');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (165, 'Yacero', 'Synergistic');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (166, 'Yata', 'pricing structure');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (167, 'Kimia', 'ability');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (168, 'Snaptags', 'Cloned');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (169, 'Yodel', 'Synergized');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (170, 'Avaveo', 'Digitized');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (171, 'Photobug', 'Function-based');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (172, 'Oloo', 'transitional');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (173, 'Tanoodle', 'Multi-tiered');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (174, 'Linklinks', 'interface');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (175, 'Rhynyx', 'asynchronous');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (176, 'Riffpedia', 'Down-sized');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (177, 'Myworks', 'Devolved');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (178, 'Dazzlesphere', 'task-force');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (179, 'Rhybox', 'Adaptive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (180, 'Bluejam', 'transitional');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (181, 'Brainbox', 'interface');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (182, 'Devpulse', 'composite');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (183, 'Jazzy', 'open architecture');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (184, 'Lazzy', 'intranet');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (185, 'Linktype', 'directional');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (186, 'Layo', 'encryption');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (187, 'Vimbo', 'optimizing');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (188, 'Topicware', 'User-friendly');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (189, 'Feedbug', 'Phased');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (190, 'Shufflebeat', 'Grass-roots');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (191, 'Fiveclub', 'Secured');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (192, 'Mybuzz', 'Quality-focused');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (193, 'Livepath', 'Multi-channelled');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (194, 'Thoughtbeat', 'disintermediate');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (195, 'Skynoodle', 'User-centric');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (196, 'Kazio', 'Right-sized');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (197, 'Zoombeat', '4th generation');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (198, 'Jaxnation', 'Customizable');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (199, 'Youspan', 'flexibility');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (200, 'Trudeo', 'multimedia');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (201, 'Dabvine', 'access');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (202, 'Nlounge', 'Advanced');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (203, 'Viva', 'hub');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (204, 'Jamia', 'parallelism');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (205, 'Pixoboo', 'system engine');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (206, 'Mybuzz', 'task-force');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (207, 'Youfeed', 'modular');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (208, 'Yozio', 'system engine');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (209, 'Brightbean', 'Operative');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (210, 'Rhyloo', 'encoding');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (211, 'Wikido', 'bi-directional');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (212, 'Dazzlesphere', 'analyzing');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (213, 'Yakitri', 'workforce');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (214, 'Dynava', 'regional');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (215, 'Skiba', 'initiative');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (216, 'Youtags', 'composite');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (217, 'Eamia', 'Expanded');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (218, 'Kwideo', 'data-warehouse');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (219, 'Skalith', 'throughput');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (220, 'Skajo', 'installation');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (221, 'Devshare', 'Front-line');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (222, 'Yakitri', 'parallelism');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (223, 'Wikibox', 'approach');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (224, 'Fatz', 'Open-architected');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (225, 'Eabox', 'client-driven');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (226, 'Trilith', 'impactful');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (227, 'Tazzy', 'project');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (228, 'Edgeify', 'maximized');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (229, 'Flashpoint', 'asymmetric');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (230, 'Thoughtmix', 'Down-sized');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (231, 'Rhycero', 'Synergized');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (232, 'Devify', 'installation');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (233, 'Roombo', 'human-resource');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (234, 'Trilith', 'knowledge user');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (235, 'Gabspot', 'cohesive');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (236, 'Youspan', 'definition');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (237, 'Realblab', 'client-driven');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (238, 'Dynabox', 'Business-focused');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (239, 'Wikibox', 'Cloned');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (240, 'Dabshots', 'Advanced');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (241, 'Mynte', 'implementation');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (242, 'Jabberstorm', 'Compatible');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (243, 'Aimbu', 'toolset');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (244, 'Eayo', 'Expanded');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (245, 'Gabtype', 'model');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (246, 'Wikizz', 'open system');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (247, 'Oodoo', 'emulation');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (248, 'Reallinks', 'array');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (249, 'Meedoo', 'encoding');
insert into Finance_Companies (finance_company_id, finance_company_name, other_details) values (250, 'Lazz', 'Seamless');
