create table Vehicle_Categories (
	vehicle_Category_Code INT,
	vehicle_Category_Description VARCHAR(25),
	PRIMARY KEY(vehicle_Category_Code)
);
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (1, 'Multi-channelled');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (2, 'even-keeled');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (3, 'homogeneous');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (4, 'Persistent');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (5, 'hardware');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (6, 'foreground');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (7, 'Pre-emptive');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (8, 'projection');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (9, 'disintermediate');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (10, 'transitional');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (11, 'directional');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (12, 'Persistent');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (13, 'Distributed');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (14, 'solution');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (15, 'Re-engineered');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (16, 'functionalities');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (17, 'well-modulated');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (18, 'Customizable');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (19, 'Realigned');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (20, 'solution');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (21, 'upward-trending');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (22, 'project');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (23, 'zero tolerance');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (24, 'Phased');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (25, 'support');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (26, '6th generation');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (27, 'strategy');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (28, 'Universal');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (29, 'Polarised');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (30, 'Monitored');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (31, 'real-time');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (32, 'secondary');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (33, 'content-based');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (34, 'projection');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (35, 'User-centric');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (36, 'systematic');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (37, 'Vision-oriented');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (38, 'Synergized');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (39, 'next generation');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (40, 'Right-sized');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (41, 'open system');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (42, 'grid-enabled');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (43, 'Configurable');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (44, 'info-mediaries');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (45, 'Streamlined');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (46, 'regional');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (47, 'Proactive');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (48, 'uniform');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (49, '6th generation');
insert into Vehicle_Categories (vehicle_category_code, vehicle_category_description) values (50, 'multimedia');
